# -*- coding: utf-8 -*-
"""breast_cancer_originalFeatures10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13qHmtrurGQR8PCphuGmSxiaYd_CA3O4R
"""

;import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import RandomOverSampler

cols = ['sample code number', 'clump thickness', 'uniformity of cell size', 'uniformity of cell shape', 'marginal adhesion',
        'single epithelial cell size', 'bare nuclei', 'balnd chromatin', 'normal nucleoli', 'mitoses', 'class']
df = pd.read_csv("breast-cancer-wisconsin.data", names=cols)
df = df.drop('sample code number', axis=1)

df['class'] = (df['class'] == 2).astype(int)
df.head(20)

for label in cols[1:-1]:
  plt.hist(df[df["class"]==1][label], color="red", label="malignant", alpha=0.7)
  plt.hist(df[df["class"]==0][label], color="blue", label="benign", alpha=0.4)
  plt.title(label)
  plt.ylabel("Probability")
  plt.xlabel(label)
  plt.legend()
  plt.show()

"""#DATA prep"""

train, valid, test = np.split(df.sample(frac=1), [int(0.6*len(df)), int(0.8*len(df))])

def scale_dataset(dataframe, oversample=False):
  X = dataframe[dataframe.columns[:-1]].values
  y = dataframe[dataframe.columns[-1]].values

  scaler = StandardScaler()
  X = scaler.fit_transform(X)

  if oversample:
    ros = RandomOverSampler()
    X, y = ros.fit_resample(X, y)

  data = np.hstack((X, np.reshape (y, (-1, 1))))
  return data, X, y

df['class'].value_counts()

train, X_train, y_train = scale_dataset(train, oversample = True)
validate, X_valid, y_valid = scale_dataset(valid, oversample = False)
test, X_test, y_test = scale_dataset(test, oversample=False)

