# -*- coding: utf-8 -*-
"""tensorflowMLmagicTELESCOPE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BRGqv5B8dNPtK7g1AZkwhk-V2nrb25M0
"""

import tensorflow as tf
print(tf.__version__)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import RandomOverSampler

cols = ["fLength", "fWidth", "fSize", "fCons", "fConc1", "fAsym", "fM3Long", "fM3Trans", "fAlpha", "fDist", "class"]
df = pd.read_csv("magic04.data", names=cols)
df.head()

df["class"] = (df["class"] == "g").astype(int)
df.head(23)

for label in cols[:-1]:
  plt.hist(df[df["class"]==1][label], color="red", label="gamma", alpha=0.7, density=True)
  plt.hist(df[df["class"]==0][label], color="blue", label="hadron", alpha=0.4, density=True)
  plt.title(label)
  plt.ylabel("Probability")
  plt.xlabel(label)
  plt.legend()
  plt.show()

"""#Training, validation and testing datasets

"""

train, validate, test = np.split(df.sample(frac=1), [int(0.6*len(df)), int(0.8*len(df))])

def scale_dataset(dataframe, oversample=False): #values are too disperse
  X = dataframe[dataframe.columns[:-1]].values
  y = dataframe[dataframe.columns[-1]].values

  scaler = StandardScaler()
  X = scaler.fit_transform(X)

  if oversample:
    ros = RandomOverSampler()
    X, y = ros.fit_resample(X, y)

  data = np.hstack((X, np.reshape (y, (-1, 1))))
  return data, X, y

len(y_train)
sum(y_train == 1)

train, X_train, y_train = scale_dataset(train, oversample = True)
validate, X_validate, y_validate = scale_dataset(validate, oversample = False)
test, X_test, y_test = scale_dataset(test, oversample=False)

"""#kNN - k-nearest neighbors

"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

knn_model = KNeighborsClassifier(n_neighbors=8)
knn_model = knn_model.fit(X_train, y_train)

y_pred = knn_model.predict(X_test)
y_pred

y_test

print(classification_report(y_test, y_pred))

"""#Naive Bayes

"""

from sklearn.naive_bayes import GaussianNB

nb_model = GaussianNB()
nb_model = nb_model.fit(X_train, y_train)

y_pred = nb_model.predict(X_test)
print(classification_report(y_test, y_pred))

"""#Log Regression

"""

from sklearn.linear_model import LogisticRegression

lg_model = LogisticRegression()
lg_model.fit(X_test, y_test)

y_pred = lg_model.predict(X_test)
print(classification_report(y_test, y_pred))

"""#SML

"""

from sklearn.svm import SVC

svm_model = SVC()
svm_model.fit(X_train, y_train)

y_pred = svm_model.predict(X_test)
print(classification_report(y_test, y_pred))

"""#Neural Network"""

import tensorflow as tf

def plot_history(history):
  fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))
  ax1.plot(history.history['loss'], label='loss')
  ax1.plot(history.history['val_loss'], label='val_loss')
  ax1.set_xlabel('Epoch')
  ax1.set_ylabel('Binary crossentropy')
  ax1.grid(True)

  ax2.plot(history.history['accuracy'], label='accuracy')
  ax2.plot(history.history['val_accuracy'], label='val_accuracy')
  ax2.set_xlabel('Epoch')
  ax2.set_ylabel('Accuracy')
  ax2.grid(True)

  plt.show()

def train_model (X_train, y_train, num_nodes, dropout_prob, lr, batch_size, epochs):
  nn_model = tf.keras.Sequential([
    tf.keras.layers.Dense(num_nodes, activation='relu', input_shape=(10, )),
    tf.keras.layers.Dropout(droput_prob),
    tf.keras.layers.Dense (num_nodes, activation = 'relu'),
    tf.keras.layers.Dropout(dropout_prob),
    tf.keras.layers.Dense(1, activation='sigmoid')
  ])


  nn_model.compile(optimizer=tf.keras.optimizers.Adam(lr), loss ='binary_crossentropy',
                 metrics=['accuracy'])
  history = nn_model.fit(
    X_train, y_train, epochs=epochs, batch_size=batch_size, validation_split=0.2, verbose=0
    ) #epochs - training cycles

  return nn_model, history

plot_history(history)